<?php

/**
 * Implements hook_theme().
 */
function my_claims_theme($existing, $type, $theme, $path) {
    return [
        'my_claims_export_button' => [
            'template' => 'my-claims-export-button',
        ],
    ];
}

// my_claims.module

/**
 * Implements hook_preprocess_HOOK() for block templates.
 */
function my_claims_preprocess_block(&$variables) {
    // Attach the library to the block.
    $variables['#attached']['library'][] = 'my_claims/my_claims';
  }
  